### ISSUE TITLE
Emails are not sent for the "Reset password" flow

### ISSUE THREAD

**Issue by weballianz** [CoderDojo/cp-users-service#305]
I want to use smtp or amazon ses instead of maildev. 

I configured the email service from the following location: /cp-local-development/workspace-zen/services/cp-email-service

In the docker-compose.yml, I've configured the AWS SES Key, secret, etc. 

I am able to send email from curl, but the zen platform cannot use this service/configuration. I received the following error:

```
> zen_1             | 2018-11-28T21:35:45.484Z p8i8t5b65rwx/1543440943888/46/- WARN       plugin  web             ACT     3qf9f5g1oegh/lldfxhxunqu7       init:web        -       -       ACT     928ldyafmsf7/lldfxhxunqu7   role:web        The method name seneca.parent is deprecated. Please use seneca.prior instead.
> zen_1             | 2018-11-28T21:36:11.465Z p8i8t5b65rwx/1543440943888/46/- WARN       plugin  transport       ACT     odvb0sefynvv/zqd4ywn24c6z       hook:client,role:transport,type:web     client      no_message_id   {type:web,port:10303,host:users,path:/act,protocol:http,timeout:119445,pin:role:cd-users,cmd:*,msgprefix:seneca {kind:res,res:null,error:Error: socket hang up,time:{client_recv:1543440971465}}
> zen_1             | 2018-11-28T21:37:58.851Z p8i8t5b65rwx/1543440943888/46/- ERROR      act     remote$         OUT             cmd:*,role:cd-users     120002  {cmd:reset_password,role:cd-users,locality:en_US,email:cristi@test.com,emailSubject:CoderDojo Zen Password R     ENTRY   CLIENT  -       seneca: Action cmd:*,role:cd-users failed: [TIMEOUT].   act_execute     {id:f6vrz8jj6yn0/0vzjc76shfl2,gate:false,ungate:false,desc:cmd:*,role:cd-users,plugin:{name:remote$,tag:null},t     Error: [TIMEOUT]
> zen_1             |     at Timeout._onTimeout (/usr/src/app/node_modules/gate-executor/gate-executor.js:95:21)
> zen_1             |     at ontimeout (timers.js:498:11)
> zen_1             |     at tryOnTimeout (timers.js:323:5)
> zen_1             |     at Timer.listOnTimeout (timers.js:290:5)
```

**Comment by Wardormeur** [comment]
Hey @weballianz 
The configuration for sending emails are fairly hardcoded : https://github.com/CoderDojo/cp-users-service/blob/master/config/config.js#L32
You might have to modify those to get SES to work
